# Generated by Django 5.2.4 on 2025-07-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogus_banks', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scrapeditem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='scrapeditem',
            name='name',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
